/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:fdfe4a18-35ab-498b-8d59-cef2f1d12dd7",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ANZ315BbC",
    "aws_user_pools_web_client_id": "3tv1sj389tsuog492bsn6cn8df",
    "oauth": {}
};


export default awsmobile;
